"use client";
import Link from "next/link";
import { ArrowLeft, ShieldAlert } from "lucide-react";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-neo-bg bg-halftone py-12 px-6">
      <div className="max-w-5xl mx-auto">
        
        {/* Navigation */}
        <Link href="/" className="inline-flex items-center gap-2 font-black uppercase mb-8 hover:-translate-y-1 transition-transform border-4 border-black bg-white px-4 py-2 shadow-neo-sm">
          <ArrowLeft className="w-5 h-5 stroke-[3px]" /> Back to Main
        </Link>

        {/* Header Badge */}
        <div className="flex items-center gap-4 mb-12 bg-white border-4 border-black p-4 sm:p-6 shadow-neo-md -rotate-1 inline-flex">
          <ShieldAlert className="h-10 w-10 sm:h-12 sm:w-12 text-black shrink-0" />
          <h1 className="text-3xl sm:text-5xl font-black uppercase tracking-tighter">
            Privacy <span className="text-neo-accent">Policy</span>
          </h1>
        </div>

        {/* Legal Document Container */}
        <div className="space-y-12 bg-white border-8 border-black p-6 sm:p-12 shadow-neo-xl">
          
          {/* Metadata */}
          <div className="bg-neo-secondary border-4 border-black p-4 font-black uppercase text-sm -rotate-1 shadow-neo-sm mb-12">
            LAST UPDATED: JUNE 13, 2026 // ENTITY: SHOP CARTEL
          </div>

          <p className="font-bold text-black/80 leading-relaxed text-sm sm:text-base">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          {/* SECTION 1 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              1. Interpretation & Definitions
            </h2>
            <div className="space-y-4 font-bold text-black/80 text-sm sm:text-base bg-neo-muted border-4 border-black p-6">
              <p><span className="font-black text-black uppercase">Account:</span> A unique account created for You to access our Service.</p>
              <p><span className="font-black text-black uppercase">Company:</span> Referred to as "the Company", "We", "Us" or "Our", refers to SHOP CARTEL.</p>
              <p><span className="font-black text-black uppercase">Cookies:</span> Small files placed on Your computer, mobile device or any other device by a website.</p>
              <p><span className="font-black text-black uppercase">Country:</span> Tamil Nadu, India.</p>
              <p><span className="font-black text-black uppercase">Device:</span> Any device that can access the Service (computer, cell phone, digital tablet).</p>
              <p><span className="font-black text-black uppercase">Personal Data:</span> Any information that relates to an identified or identifiable individual.</p>
              <p><span className="font-black text-black uppercase">Service:</span> Refers to the Website (SHOP CARTEL, accessible from https://e-commerce-chi-three-54.vercel.app/).</p>
              <p><span className="font-black text-black uppercase">Usage Data:</span> Data collected automatically, generated by the use of the Service infrastructure.</p>
            </div>
          </section>

          {/* SECTION 2 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              2. Collecting Your Personal Data
            </h2>
            <h3 className="text-xl font-black uppercase tracking-tight">Types of Data Collected</h3>
            <p className="font-bold text-black/80 text-sm sm:text-base">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This includes, but is not limited to:
            </p>
            <ul className="list-square list-inside space-y-2 font-bold text-black/80 ml-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data (IP address, browser type, pages visited, time spent, diagnostic data)</li>
            </ul>
          </section>

          {/* SECTION 3 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              3. Database & Tracking Technologies
            </h2>
            <p className="font-bold text-black/80 text-sm sm:text-base">
              We use Cookies and similar tracking technologies to track activity and store certain information. However, unlike standard systems, <span className="font-black text-black uppercase bg-yellow-300 px-1">Your active cart and session state are synchronized securely with our encrypted backend servers (MongoDB).</span> Local browser storage is strictly used for temporary, encrypted JSON Web Tokens (JWT) and essential functional cookies.
            </p>
            <ul className="list-square list-inside space-y-2 font-bold text-black/80 ml-4">
              <li><span className="font-black text-black uppercase">Necessary Cookies:</span> Essential to authenticate users and prevent fraudulent use.</li>
              <li><span className="font-black text-black uppercase">Acceptance Cookies:</span> Identifies if users have accepted the use of cookies.</li>
              <li><span className="font-black text-black uppercase">Functionality Cookies:</span> Remembers choices You make (login details, language).</li>
            </ul>
          </section>

          {/* SECTION 4 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              4. Use & Disclosure of Your Data
            </h2>
            <p className="font-bold text-black/80 text-sm sm:text-base">
              The Company may use Personal Data to provide and maintain our Service, manage Your Account, perform purchase contracts, and contact You regarding updates. We may share Your Personal Data in the following situations:
            </p>
            <ul className="list-square list-inside space-y-2 font-bold text-black/80 ml-4">
              <li><span className="font-black text-black">With Service Providers:</span> To monitor and analyze the use of our Service, or process secure payments (e.g., Stripe).</li>
              <li><span className="font-black text-black">For Business Transfers:</span> During negotiations of any merger, sale, or acquisition.</li>
              <li><span className="font-black text-black">Law Enforcement:</span> Under certain circumstances, we may be required to disclose Your Personal Data if required by law or valid requests by public authorities.</li>
            </ul>
          </section>

          {/* SECTION 5 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              5. Retention & Deletion
            </h2>
            <p className="font-bold text-black/80 text-sm sm:text-base">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy (up to 24 months after account closure for standard data). You have the right to delete or request that We assist in deleting the Personal Data We have collected. You may update, amend, or delete Your information at any time by signing in to Your Account settings.
            </p>
          </section>

          {/* SECTION 6 */}
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black uppercase tracking-widest border-b-4 border-black pb-2 text-black">
              6. Security & Children's Privacy
            </h2>
            <p className="font-bold text-black/80 text-sm sm:text-base">
              While We strive to use commercially reasonable means to protect Your Personal Data, remember that no method of electronic transmission is 100% secure. Furthermore, Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under 16 without verification of parental consent.
            </p>
          </section>

          {/* FOOTER */}
          <div className="bg-black text-white border-4 border-black p-8 mt-12 shadow-[8px_8px_0px_0px_rgba(239,68,68,1)]">
            <h3 className="text-2xl font-black uppercase tracking-widest mb-4">Contact Terminal</h3>
            <p className="font-bold text-white/80 mb-4">
              If you have any questions about this Privacy Policy, initiate a transmission to our operations team:
            </p>
            <a href="mailto:shopcartel91@gmail.com" className="inline-block bg-neo-accent text-black px-6 py-3 font-black uppercase tracking-widest border-4 border-black hover:bg-white transition-colors">
              shopcartel91@gmail.com
            </a>
          </div>

        </div>
      </div>
    </main>
  );
}